import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { STORAGE_DRIVER, StorageDriver } from '../documents/storage/storage.interface';
import PDFDocument = require('pdfkit');

const SUPPORTED_FORMS = new Set(['1099-INT', '1099-MISC']);

@Injectable()
export class TaxFormsService {
  constructor(
    private readonly prisma: PrismaService,
    @Inject(STORAGE_DRIVER) private readonly storage: StorageDriver,
  ) {}

  async listForUser(userId: string) {
    const rows = await this.prisma.taxForm.findMany({
      where: { userId },
      orderBy: [{ taxYear: 'desc' }, { formType: 'asc' }],
    });
    return rows.map((r) => ({
      id: r.id,
      formType: r.formType,
      taxYear: r.taxYear,
      sizeBytes: r.sizeBytes,
      generatedAt: r.generatedAt.toISOString(),
    }));
  }

  async downloadUrl(userId: string, id: string): Promise<string> {
    const row = await this.prisma.taxForm.findUnique({ where: { id } });
    if (!row || row.userId !== userId) throw new NotFoundException('Form not found');
    return this.storage.getPresignedDownloadUrl(row.storageKey);
  }

  async generate(userId: string, formType: string, taxYear: number) {
    if (!SUPPORTED_FORMS.has(formType)) throw new BadRequestException('Unsupported form type');

    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) throw new NotFoundException('User not found');

    const start = new Date(Date.UTC(taxYear, 0, 1));
    const end = new Date(Date.UTC(taxYear + 1, 0, 1));
    const interestRows = await this.prisma.transaction.findMany({
      where: {
        account: { userId },
        status: 'posted',
        kind: 'interest',
        occurredAt: { gte: start, lt: end },
      },
      select: { amountCents: true },
    });
    const interestCents = interestRows.reduce((a, t) => a + t.amountCents, 0n);

    const pdf = await this.render({
      formType,
      taxYear,
      payerName: 'State Bank',
      payerTin: 'XX-XXXXXXX',
      recipientName: [user.firstName, user.lastName].filter(Boolean).join(' ') || user.email,
      recipientTinLast4: 'XXXX',
      amountCents: interestCents,
    });

    const key = `tax/${userId}/${taxYear}/${formType}.pdf`;
    await this.storage.put({ key, body: pdf, contentType: 'application/pdf' });

    return this.prisma.taxForm.upsert({
      where: { userId_formType_taxYear: { userId, formType, taxYear } },
      update: { storageKey: key, sizeBytes: pdf.length, generatedAt: new Date() },
      create: { userId, formType, taxYear, storageKey: key, sizeBytes: pdf.length },
    });
  }

  private render(vars: {
    formType: string;
    taxYear: number;
    payerName: string;
    payerTin: string;
    recipientName: string;
    recipientTinLast4: string;
    amountCents: bigint;
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'LETTER', margin: 56 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(18).text(`${vars.formType} — Tax Year ${vars.taxYear}`, { align: 'center' });
      doc.moveDown(1.5);
      doc.fontSize(11);
      doc.text(`Payer:     ${vars.payerName}`);
      doc.text(`Payer TIN: ${vars.payerTin}`);
      doc.moveDown(0.5);
      doc.text(`Recipient:        ${vars.recipientName}`);
      doc.text(`Recipient TIN:    ***-**-${vars.recipientTinLast4}`);
      doc.moveDown(1);
      doc.fontSize(13).text('Reportable amount', { underline: true });
      doc.fontSize(12).text(`$${(Number(vars.amountCents) / 100).toFixed(2)}`);
      doc.moveDown(2);
      doc.fontSize(9).text(
        'This document is generated by State Bank for your records. Retain it for your tax filing. If you have questions about the amounts shown, contact State Bank Support.',
        { align: 'justify' },
      );
      doc.end();
    });
  }
}
